repos:
  - repo: https://github.com/losisin/helm-values-schema-json
    rev: v2.3.1
    hooks:
      - id: helm-schema
        args:
          [
            "--values",
            "helm/hello-world/values.yaml",
            "-o",
            "helm/hello-world/values.schema.json",
            "--use-helm-docs",
            "--bundle",
            "--no-additional-properties",
          ]
  - repo: https://github.com/norwoodj/helm-docs
    rev: "v1.14.2"
    hooks:
      - id: helm-docs
        args:
          - --chart-search-root=helm
