apiVersion: v2
name: hello-world-app
version: "0.1.0"
appVersion: 0.1.0
home: https://github.com/giantswarm/hello-world-app
description: A chart that deploys a basic hello world site and lets you test values merging of user values configmap and secrets.
icon: https://s.giantswarm.io/app-icons/1/png/hello-world-app-light.png
