apiVersion: v2
name: hello-world
description: A chart that deploys a basic hello world site and lets you test values merging of user values configmap and secrets.
type: application
version: 2.11.0
appVersion: "0.3.0"
home: https://github.com/giantswarm/hello-world-app
icon: https://s.giantswarm.io/app-icons/1/png/hello-world-app-light.png
keywords:
  - demo
  - webapp
  - testing
sources:
  - https://github.com/giantswarm/helloworld
annotations:
  io.giantswarm.application.audience: all
  io.giantswarm.application.managed: "false"
  io.giantswarm.application.team: honeybadger
